baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Amber Thrall'
theme = "hugo-coder"

[pagination]
pagerSize = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[markup.highlight]
style = "github-dark"

[params]
math = true
author = "Amber Thrall"
info = "Mathematician and Computer Scientist"
description = "Amber Thrall's personal website"
avatarurl = "images/440050.jpg"
favicon = "/images/favicon.ico"
colorScheme = "dark"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/AmberThrall/"

# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Research"
weight = 2
url = "research/"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[menu.main]]
name = "Contact Me"
weight = 4
url  = "contact/"

[[menu.main]]
name = "Blog"
weight = 5
url  = "posts/"
